
name: release

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/release.yml'
      - '.version'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.8'
      - id: build
        run: |
          make buildx
          echo "::set-output name=version::v$(cat .version)"
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.version }}
          release_name: Release ${{ steps.build.outputs.version }}
          draft: false
          prerelease: false
      - uses: csexton/release-asset-action@v2
        with:
          pattern: bin/*
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
